---
- name: Upgrade rhevm to lastest version
  hosts: bad40

  roles:
    - { role: roles/rhevm_upgrade/mark_host_status, cmd: '{"$set":{"status":"upgrading"}}' }
    - roles/common/unregister_rhn_sm
    - roles/rhevm_upgrade/pre
    - roles/rhevm_upgrade/rhevm4x
    - { role: roles/rhevm_upgrade/mark_host_status, cmd: '{"$set":{"status":"running"}}' }
